"""add favourite

Revision ID: 0c788e686312
Revises: 21c771768c35
Create Date: 2024-05-27 20:54:33.401813

"""
import uuid
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c788e686312'
down_revision: Union[str, None] = '21c771768c35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('psalm_books', sa.Column('icon_src', sa.String(), nullable=True))
    op.add_column('psalm_books', sa.Column('is_favourite', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###
    op.execute(
        """
        INSERT INTO psalm_books (id, name, icon_src, is_favourite, language) 
        VALUES ('{}', 'Favourite', NULL, 1, 'unk')
        """.format(str(uuid.uuid4()))
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('psalm_books', 'is_favourite')
    op.drop_column('psalm_books', 'icon_src')
    # ### end Alembic commands ###
    op.execute(
        """
        DELETE FROM psalm_books WHERE name = 'Favourite' AND language = 'unk'
        """
    )
