"""add last usage

Revision ID: 12b9bef38048
Revises: e9e4960cbd8e
Create Date: 2024-01-28 04:23:35.259037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12b9bef38048'
down_revision: Union[str, None] = 'e9e4960cbd8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verses', sa.Column('last_usage', sa.DateTime(), nullable=True))
    op.add_column('verses', sa.Column('usages_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('verses', 'usages_count')
    op.drop_column('verses', 'last_usage')
    # ### end Alembic commands ###
