"""add translation to bible

Revision ID: 4d098eb1f260
Revises: 415e2b4b76fc
Create Date: 2024-01-28 02:51:21.516266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d098eb1f260'
down_revision: Union[str, None] = '415e2b4b76fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bibles', sa.Column('translation', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bibles', 'translation')
    # ### end Alembic commands ###
