"""AddCoupletStyling

Revision ID: 53229d50ecb5
Revises: 1106c83ea427
Create Date: 2024-06-21 01:58:14.156392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53229d50ecb5'
down_revision: Union[str, None] = '1106c83ea427'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('couplets', sa.Column('styling', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('couplets', 'styling')
    # ### end Alembic commands ###
