"""add bible mappings

Revision ID: 5ad8daba286c
Revises: 912d28452330
Create Date: 2024-09-02 05:05:46.872129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ad8daba286c'
down_revision: Union[str, None] = '912d28452330'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bible_books_mappings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('bible_book_id', sa.String(length=36), nullable=False),
    sa.Column('global_bible_book_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['bible_book_id'], ['bible_books.id'], ),
    sa.ForeignKeyConstraint(['global_bible_book_id'], ['bible_books.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bible_books_mappings')
    # ### end Alembic commands ###
