"""add_psalm_order

Revision ID: 912d28452330
Revises: 53229d50ecb5
Create Date: 2024-06-30 02:06:48.522985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '912d28452330'
down_revision: Union[str, None] = '53229d50ecb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('psalms_book_psalms', sa.Column('order', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('psalms_book_psalms', 'order')
    # ### end Alembic commands ###
