"""add created_at field in sermon

Revision ID: b6e5be02855c
Revises: 93f1dc1961f2
Create Date: 2024-01-29 00:33:54.335589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6e5be02855c'
down_revision: Union[str, None] = '93f1dc1961f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sermons', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sermons', 'created_at')
    # ### end Alembic commands ###
